neighborhoods = (
    ("Bishan East","Bishan East"),
("Marymount","Marymount"),
("Upper Thomson","Upper Thomson"),
("Alexandra Hill","Alexandra Hill"),
("Alexandra North","Alexandra North"),
("Bukit Ho Swee","Bukit Ho Swee"),
("Bukit Merah","Bukit Merah"),
("City Terminals","City Terminals"),
("Depot Road","Depot Road"),
("Everton Park","Everton Park"),
("Henderson Hill","Henderson Hill"),
("Kampong Tiong Bahru","Kampong Tiong Bahru"),
("Maritime Square","Maritime Square"),
("Redhill","Redhill"),
("Singapore General Hospital","Singapore General Hospital"),
("Telok Blangah Drive","Telok Blangah Drive"),
("Telok Blangah Rise","Telok Blangah Rise"),
("Telok Blangah Way","Telok Blangah Way"),
("Tiong Bahru","Tiong Bahru"),
("Tiong Bahru Station","Tiong Bahru Station"),
("Anak Bukit","Anak Bukit"),
("Coronation Road","Coronation Road"),
("Farrer Court","Farrer Court"),
("Hillcrest","Hillcrest"),
("Holland Road","Holland Road"),
("Leedon Park","Leedon Park"),
("Swiss Club","Swiss Club"),
("Ulu Pandan","Ulu Pandan"),
("Anson","Anson"),
("Bayfront Subzone","Bayfront Subzone"),
("Bugis","Bugis"),
("Cecil","Cecil"),
("Central Subzone","Central Subzone"),
("City Hall","City Hall"),
("Clifford Pier","Clifford Pier"),
("Marina Centre","Marina Centre"),
("Maxwell","Maxwell"),
("Nicoll","Nicoll"),
("Phillip","Phillip"),
("Raffles Place","Raffles Place"),
("Tanjong Pagar","Tanjong Pagar"),
("Aljunied","Aljunied"),
("Geylang East","Geylang East"),
("Kallang Way","Kallang Way"),
("Kampong Ubi","Kampong Ubi"),
("MacPherson","MacPherson"),
("Bendemeer","Bendemeer"),
("Boon Keng","Boon Keng"),
("Crawford","Crawford"),
("Geylang Bahru","Geylang Bahru"),
("Kallang Bahru","Kallang Bahru"),
("Kampong Bugis","Kampong Bugis"),
("Kampong Java","Kampong Java"),
("Lavender","Lavender"),
("Tanjong Rhu","Tanjong Rhu"),
("Marina East","Marina East"),
("Marina South","Marina South"),
("East Coast","East Coast"),
("Katong","Katong"),
("Marina East","Marina East"),
("Marine Parade","Marine Parade"),
("Mountbatten","Mountbatten"),
("Bras Basah","Bras Basah"),
("Dhoby Ghaut","Dhoby Ghaut"),
("Fort Canning","Fort Canning"),
("Cairnhill","Cairnhill"),
("Goodwood Park","Goodwood Park"),
("Istana Negara","Istana Negara"),
("Monk's Hill","Monk's Hill"),
("Newton Circus","Newton Circus"),
("Orange Grove","Orange Grove"),
("Balestier","Balestier"),
("Dunearn","Dunearn"),
("Malcolm","Malcolm"),
("Moulmein","Moulmein"),
("Mount Pleasant","Mount Pleasant"),
("Boulevard","Boulevard"),
("Somerset","Somerset"),
("Tanglin","Tanglin"),
("China Square","China Square"),
("Chinatown","Chinatown"),
("Pearl's Hill","Pearl's Hill"),
("People's Park","People's Park"),
("Commonwealth","Commonwealth"),
("Dover","Dover"),
("Ghim Moh","Ghim Moh"),
("Holland Drive","Holland Drive"),
("Kent Ridge","Kent Ridge"),
("Margaret Drive","Margaret Drive"),
("Mei Chin","Mei Chin"),
("National University of Singapore","National University of Singapore"),
("one-north","one-north"),
("Pasir Panjang 1","Pasir Panjang 1"),
("Pasir Panjang 2","Pasir Panjang 2"),
("Port","Port"),
("Queensway","Queensway"),
("Singapore Polytechnic","Singapore Polytechnic"),
("Tanglin Halt","Tanglin Halt"),
("Institution Hill","Institution Hill"),
("Leonie Hill","Leonie Hill"),
("One Tree Hill","One Tree Hill"),
("Oxley","Oxley"),
("Paterson","Paterson"),
("Bencoolen","Bencoolen"),
("Farrer Park","Farrer Park"),
("Kampong Glam","Kampong Glam"),
("Little India","Little India"),
("Mackenzie","Mackenzie"),
("Mount Emily","Mount Emily"),
("Rochor Canal","Rochor Canal"),
("Selegie","Selegie"),
("Sungei Road","Sungei Road"),
("Victoria","Victoria"),
("Boat Quay","Boat Quay"),
("Clarke Quay","Clarke Quay"),
("Robertson Quay","Robertson Quay"),
("Sentosa","Sentosa"),
("Southern Group","Southern Group"),
("Straits View","Straits View"),
("Chatsworth","Chatsworth"),
("Nassim","Nassim"),
("Ridout","Ridout"),
("Tyersall","Tyersall"),
("Bidadari","Bidadari"),
("Boon Teck","Boon Teck"),
("Braddell","Braddell"),
("Joo Seng","Joo Seng"),
("Kim Keat","Kim Keat"),
("Lorong 8 Toa Payoh","Lorong 8 Toa Payoh"),
("Pei Chun","Pei Chun"),
("Potong Pasir","Potong Pasir"),
("Sennett","Sennett"),
("Toa Payoh Central","Toa Payoh Central"),
("Toa Payoh West","Toa Payoh West"),
)