# Generated by Django 3.2.13 on 2022-07-22 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowuser',
            name='display_img',
            field=models.ImageField(blank=True, default='uploads/userprofile/default_profile_img.png', upload_to='uploads/userprofile/'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/posts/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
