# Generated by Django 3.2.13 on 2022-07-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220722_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowuser',
            name='display_img',
            field=models.ImageField(blank=True, default='default_profile_img.png', upload_to='profile/'),
        ),
    ]
